services:
  math-factory-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: math-factory-server
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
  math-factory-client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: math-factory-client
    depends_on:
      - math-factory-server
    environment:
      PYTHONPATH: /app/src

