FROM python:3.11-slim

WORKDIR /app
COPY src /app/src

ENV PYTHONPATH=/app/src
ENV PYTHONUNBUFFERED=1

CMD [
  "python",
  "-m",
  "math_factory.client",
  "--server-host",
  "math-factory-server",
  "--terms",
  "8",
  "--threshold",
  "2500"
]

