services:
  c1:
    build: .
    environment:
      - SEND_ADDRESS=c2:8080
      - LISTEN_ADDRESS=0.0.0.0:8080
      - OPERATION=inc
      - SOCKETTYPE=udp
    extra_hosts:
      - "host.docker.internal:172.19.0.1"
    depends_on:
      - c2

  c2:
    build: .
    environment:
      - SEND_ADDRESS=c3:8080
      - LISTEN_ADDRESS=0.0.0.0:8080
      - OPERATION=shl
      - SOCKETTYPE=udp
    extra_hosts:
      - "host.docker.internal:172.19.0.1"
    depends_on:
      - c3

  c3:
    build: .
    environment:
      - SEND_ADDRESS=host.docker.internal:8080
      - LISTEN_ADDRESS=0.0.0.0:8080
      - OPERATION=dec
      - SOCKETTYPE=udp
    extra_hosts:
      - "host.docker.internal:172.19.0.1"
